#diretrizes_por_nivel_e_objetivo = { 'iniciante' :   { 'forca_maxima' : { 'intensidade': '8-12RM sem falha (60-70%FM)',
                                                                        'numero_de_series': '1-3 series por exercicio',
                                                                        'intervalo': '1:2 minutos', 'velocidade_do_movimento':'lenta moderada',
                                                                        'frequencia semanal': '2 a 3 para todo o corpo'},
                                                    'forca_hipertrofica' : { 'intensidade': '8-12RM sem falha (70-85%FM)',
                                                                         'numero_de_series': '1-3 series por exercicio',
                                                                         'intervalo': '1:2 minutos', 'velocidade_do_movimento':'moderada',
                                                                         'frequencia semanal': '2 a 3 para todo o corpo' },
                                                    'forca_explosiva' : { 'intensidade': '3 a 6RM sem falha (30 a 60%FM- MMSS) e 0 a 60% MMII',
                                                                         'numero_de_series': '1-3 series por exercicio',
                                                                         'intervalo': '2 a 3 intensidade alta e 1:2 minutos intensidade leve',
                                                                         'velocidade_do_movimento': 'moderada a rapida',
                                                                         'frequencia semanal': '2 a 3 para todo o corpo' },
                                                    'resistencia_de_forca' : { 'intensidade': '10 a 15RM',
                                                                         'numero_de_series': '1-3 series por exercicio',
                                                                         'intervalo': '< 1 minutos', 'velocidade_do_movimento': 'lenta ',
                                                                         'frequencia semanal': '2 a 3 para todo o corpo' },
                                    },
                                    { 'intermediario':  {  'forca_maxima' : { 'intensidade': '8 a 12 sem falha (60-70%FM)',
                                                                         'numero_de_series': 'multiplas', 'intervalo': '1:2 minutos',
                                                                         'velocidade_do_movimento':'moderada',
                                                                         'frequencia semanal': '3 a 4 com parcelamento dos grupos musculares' },
                                                    'forca_hipertrofica' : { 'intensidade': '8 a 12 sem falha (70-85%FM)',
                                                                         'numero_de_series': '1-3', 'intervalo': '1:2 minutos',
                                                                         'velocidade_do_movimento':'moderada',
                                                                         'frequencia semanal': '4x (2x MMSS / 2x MMII)' },
                                                    'forca_explosiva' : { 'intensidade': '3 a 6 sem falha, 30-60% FM(MMSS) 0-60%FM(MMII)',
                                                                         'numero_de_series': '1-3',
                                                                         'intervalo': '2 a 3 (intensidade alta),  1 a 2 (intensidade leve)',
                                                                         'velocidade_do_movimento':'rapida',
                                                                         'frequencia semanal': '3 a 4 com parcelamento dos grupos musculares' },
                                                    'resistencia_de_forca' : { 'intensidade': '10 a 15RM',
                                                                         'numero_de_series': '1-3', 'intervalo': '<1', 'velocidade_do_movimento':'lenta',
                                                                         'frequencia semanal': '3 a 4 com parcelamento dos grupos musculares' },
    },
                                    'avancado' : { 'forca_maxima' : { 'intensidade': '1 a 6RM (80-100%FM)', 'numero_de_series': 'multiplas',
                                                                         'intervalo': '2 a 3 (intensidade alta), 1 a 2 (intensidade leve)',
                                                                         'velocidade_do_movimento':'lenta a rápida',
                                                                         'frequencia_semanal': '4:6 (com parcelamento dos grupos MM)' },
                                                    'forca_hipertrofica' : { 'intensidade': '1 a 12RM (70-100%FM)(ênfase 6-12RM)',
                                                                         'numero_de_series': '3-6 series por exercicio',
                                                                         'intervalo': '2 a 3 (intensidade alta), 1 a 2 (intensidade leve)',
                                                                         'velocidade_do_movimento':'lenta a rapida',
                                                                         'frequencia_semanal': '4:6 (com parcelamento dos grupos MM)' },
                                                    'forca_explosiva' : { 'intensidade': '85 a 100% -> força / 30 a 60%1 -> velocidade',
                                                                         'numero_de_series': '3-6 series por exercicio',
                                                                         'intervalo': '2 a 3 (intensidade alta), 1 a 2 (intensidade leve)' ,
                                                                         'velocidade_do_movimento': 'rapida',
                                                                         'frequencia_semanal': '4:5 para todo corpor ou parcelando MMSS e MMII' },
                                                    'resistencia_de_forca' : { 'intensidade': '>15RM', 'numero_de_series': 'multiplas',
                                                                         'intervalo': '1:2 minutos' , 'velocidade_do_movimento': 'moderada a rapida',
                                                                         'frequencia_semanal': '4:6 com parcelamento dos grupos MM' },
    }
}